package sistema;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dani
 */
public class TelaInicial extends javax.swing.JFrame {

    BufferedImage buffer_In = null;
    BufferedImage bufferOut = null;
    BufferedImage bufferOriginal = null;

    public TelaInicial() {
        initComponents();
        carregarImagemDefault();
        ativarBotoesNoPainel(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirArquivoDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_04 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton_02 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton_03 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton_05 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonColorizacaoRed = new javax.swing.JButton();
        jButtonColorizacaoGreen = new javax.swing.JButton();
        jButtonColorizacaoBlue = new javax.swing.JButton();
        jLabelEditorOrg = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout abrirArquivoDialogLayout = new javax.swing.GroupLayout(abrirArquivoDialog.getContentPane());
        abrirArquivoDialog.getContentPane().setLayout(abrirArquivoDialogLayout);
        abrirArquivoDialogLayout.setHorizontalGroup(
            abrirArquivoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        abrirArquivoDialogLayout.setVerticalGroup(
            abrirArquivoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computação Gráfica I - Daniela");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO THRESHOLD"));

        jButton_04.setText("APLICAR");
        jButton_04.setToolTipText("Definir como Threshold");
        jButton_04.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_04.setBorderPainted(false);
        jButton_04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_04.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO CINZA"));

        jButton_02.setText("APLICAR");
        jButton_02.setToolTipText("Definir como Cinza");
        jButton_02.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_02.setBorderPainted(false);
        jButton_02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_02.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_02, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO SÉPIA"));

        jButton_03.setText("APLICAR");
        jButton_03.setToolTipText("Definir como Sépia");
        jButton_03.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_03.setBorderPainted(false);
        jButton_03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_03.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_03, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO NEGATIVA"));

        jButton_05.setText("APLICAR");
        jButton_05.setToolTipText("Definir como Negativa");
        jButton_05.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_05.setBorderPainted(false);
        jButton_05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_05.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_05ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_05, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("IMAGEM ORIGINAL")));

        jButton_1.setText("APLICAR");
        jButton_1.setToolTipText("Definir para imagem original");
        jButton_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_1.setBorderPainted(false);
        jButton_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO COLORIZAÇÃO"));

        jButtonColorizacaoRed.setBackground(new java.awt.Color(255, 0, 0));
        jButtonColorizacaoRed.setToolTipText("Definir Colorização");
        jButtonColorizacaoRed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoRed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoRed.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoRed.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoRedActionPerformed(evt);
            }
        });

        jButtonColorizacaoGreen.setBackground(new java.awt.Color(0, 255, 0));
        jButtonColorizacaoGreen.setToolTipText("Definir Colorização");
        jButtonColorizacaoGreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoGreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoGreen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoGreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoGreenActionPerformed(evt);
            }
        });

        jButtonColorizacaoBlue.setBackground(new java.awt.Color(0, 0, 255));
        jButtonColorizacaoBlue.setToolTipText("Definir Colorização");
        jButtonColorizacaoBlue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoBlue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoBlue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoBlue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoBlueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonColorizacaoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonColorizacaoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonColorizacaoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonColorizacaoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorizacaoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorizacaoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelEditorOrg.setBackground(new java.awt.Color(71, 71, 71));
        jLabelEditorOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditorOrg.setToolTipText("");
        jLabelEditorOrg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabelEditorOrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelEditorOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelEditorOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("ABRIR IMAGEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALVAR IMAGEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("FECHAR IMAGEM NO PAINEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SAIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void abrirArquivo() {
        try {
            JFileChooser fc = new JFileChooser();
            FileFilter imageFilter = new FileNameExtensionFilter(
                    "Image files", ImageIO.getReaderFileSuffixes());
            fc.setFileFilter(imageFilter);
            fc.setDialogTitle("Abrir novo arquivo");
            int result = fc.showOpenDialog(null);
            if (result == 0) {
                ativarBotoesNoPainel(true);
                String filename = fc.getSelectedFile().getAbsolutePath();
                buffer_In = ImageIO.read(new File(filename));
                bufferOut = buffer_In;
                bufferOriginal = buffer_In;
                Image dimg = buffer_In.getScaledInstance(jLabelEditorOrg.getWidth(), jLabelEditorOrg.getHeight(),
                        Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                jLabelEditorOrg.setIcon(imageIcon);
                jLabelEditorOrg.setText(null);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void drowImageInLabelEditor(BufferedImage bufferInputIn) {
        Image pdi = buffer_In.getScaledInstance(jLabelEditorOrg.getWidth(), jLabelEditorOrg.getHeight(),
                Image.SCALE_SMOOTH);
        jLabelEditorOrg.setIcon(new ImageIcon(((new ImageIcon(bufferInputIn))
                .getImage().getScaledInstance(jLabelEditorOrg.getWidth(),
                        jLabelEditorOrg.getHeight(), Image.SCALE_SMOOTH))));
    }

    void ativarBotoesNoPainel(boolean disabled) {
        jButton_02.setEnabled(disabled);
        jButton_05.setEnabled(disabled);
        jButton_03.setEnabled(disabled);
        jButton_04.setEnabled(disabled);
        jButton_1.setEnabled(disabled);
        jButtonColorizacaoRed.setEnabled(disabled);
        jButtonColorizacaoGreen.setEnabled(disabled);
        jButtonColorizacaoBlue.setEnabled(disabled);
    }

    private void jButton_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_02ActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroCinza(buffer_In);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButton_02ActionPerformed

    private void jButton_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_03ActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroSepia(buffer_In);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButton_03ActionPerformed

    private void jButton_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_04ActionPerformed

        bufferOut = new FiltrosCG_I().filtroThreshold(buffer_In);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButton_04ActionPerformed

    private void jButton_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_05ActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroNegativa(buffer_In);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButton_05ActionPerformed

    void carregarImagemDefault() {
        jLabelEditorOrg.setIcon(new ImageIcon(((new ImageIcon(getClass().getResource("/sistema/white.png")).getImage()
                .getScaledInstance(600, 600, Image.SCALE_SMOOTH)))));
    }
    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
        drowImageInLabelEditor(bufferOriginal);
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButtonColorizacaoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoRedActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroColorizacao(buffer_In, 1);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoRedActionPerformed

    private void jButtonColorizacaoBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoBlueActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroColorizacao(buffer_In, 2);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoBlueActionPerformed

    private void jButtonColorizacaoGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoGreenActionPerformed
        // TODO add your handling code here:
        bufferOut = new FiltrosCG_I().filtroColorizacao(buffer_In, 3);
        drowImageInLabelEditor(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoGreenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abrirArquivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (bufferOut == null) {
            JOptionPane.showMessageDialog(null, "Selecione alguma imagem, por favor", "Atenção", 1);
        } else {
            new FiltrosCG_I().salvarArquivoNoDisco(bufferOut, "imagem.jpeg");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        carregarImagemDefault();
        ativarBotoesNoPainel(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog abrirArquivoDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonColorizacaoBlue;
    private javax.swing.JButton jButtonColorizacaoGreen;
    private javax.swing.JButton jButtonColorizacaoRed;
    private javax.swing.JButton jButton_02;
    private javax.swing.JButton jButton_03;
    private javax.swing.JButton jButton_04;
    private javax.swing.JButton jButton_05;
    private javax.swing.JButton jButton_1;
    private javax.swing.JLabel jLabelEditorOrg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
