/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Taffarel
 */
public class TelaInicial extends javax.swing.JFrame {

    BufferedImage bufferIn, bufferOut, bufferOriginal = null;
    private String nomeDoArquivoSalvar = null;

    /**
     * Creates new form TelaInicial
     */
    void setIconButton(JButton button, String fileName) {
        button.setIcon(new ImageIcon(((new ImageIcon(getClass().getResource("/imagens/" + fileName)).getImage()
                .getScaledInstance(120, 120, Image.SCALE_SMOOTH)))));
    }

    void ativarBotoesNoPainel(boolean disabled) {
        jButtonCinza.setEnabled(disabled);
        jButtonNegativa.setEnabled(disabled);
        jButtonSepia.setEnabled(disabled);
        jButtonThreshold.setEnabled(disabled);
        jButtonOriginal.setEnabled(disabled);
        jButtonColorizacaoRed.setEnabled(disabled);
        jButtonColorizacaoGreen.setEnabled(disabled);
        jButtonColorizacaoBlue.setEnabled(disabled);
    }

    public TelaInicial() {
        initComponents();
        definirImagemPadrao();
        ativarBotoesNoPainel(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirArquivoDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonColorizacaoGreen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonThreshold = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonCinza = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonSepia = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonNegativa = new javax.swing.JButton();
        jButtonColorizacaoRed = new javax.swing.JButton();
        jButtonColorizacaoBlue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonOriginal = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout abrirArquivoDialogLayout = new javax.swing.GroupLayout(abrirArquivoDialog.getContentPane());
        abrirArquivoDialog.getContentPane().setLayout(abrirArquivoDialogLayout);
        abrirArquivoDialogLayout.setHorizontalGroup(
            abrirArquivoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        abrirArquivoDialogLayout.setVerticalGroup(
            abrirArquivoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de imagens Simples - Compução Gráfia I - Professor Moisés");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setBackground(new java.awt.Color(71, 71, 71));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("Clique aqui para abrir o arquivo");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonColorizacaoGreen.setBackground(new java.awt.Color(0, 255, 0));
        jButtonColorizacaoGreen.setToolTipText("Definir Colorização");
        jButtonColorizacaoGreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoGreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoGreen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoGreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoGreenActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO Threshold"));

        jButtonThreshold.setText("APLICAR");
        jButtonThreshold.setToolTipText("Definir como Threshold");
        jButtonThreshold.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonThreshold.setBorderPainted(false);
        jButtonThreshold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonThreshold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThresholdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonThreshold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("CINZA"));

        jButtonCinza.setText("APLICAR");
        jButtonCinza.setToolTipText("Definir como Cinza");
        jButtonCinza.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCinza.setBorderPainted(false);
        jButtonCinza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCinza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCinzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCinza, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO SÉPIA"));

        jButtonSepia.setText("APLICAR");
        jButtonSepia.setToolTipText("Definir como Sépia");
        jButtonSepia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSepia.setBorderPainted(false);
        jButtonSepia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSepia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSepiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSepia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSepia, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTRO NEGATIVA"));

        jButtonNegativa.setText("APLICAR");
        jButtonNegativa.setToolTipText("Definir como Negativa");
        jButtonNegativa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNegativa.setBorderPainted(false);
        jButtonNegativa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNegativa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNegativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNegativa, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNegativa, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jButtonColorizacaoRed.setBackground(new java.awt.Color(255, 0, 0));
        jButtonColorizacaoRed.setToolTipText("Definir Colorização");
        jButtonColorizacaoRed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoRed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoRed.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoRed.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoRedActionPerformed(evt);
            }
        });

        jButtonColorizacaoBlue.setBackground(new java.awt.Color(0, 0, 255));
        jButtonColorizacaoBlue.setToolTipText("Definir Colorização");
        jButtonColorizacaoBlue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonColorizacaoBlue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorizacaoBlue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoBlue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorizacaoBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorizacaoBlueActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("IMAGEM ORIGINAL")));

        jButtonOriginal.setText("APLICAR");
        jButtonOriginal.setToolTipText("Definir para imagem original");
        jButtonOriginal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonOriginal.setBorderPainted(false);
        jButtonOriginal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOriginal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOriginalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jButtonColorizacaoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonColorizacaoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonColorizacaoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonColorizacaoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorizacaoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorizacaoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("FILTRO Threshold");

        jButton1.setText("ABRIR IMAGEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALVAR IMAGEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("FECHAR IMAGEM NO PAINEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void abrirArquivo() {
        try {
            JFileChooser fileChooser = new JFileChooser();
            FileFilter imageFilter = new FileNameExtensionFilter(
                    "Image files", ImageIO.getReaderFileSuffixes());
            fileChooser.setFileFilter(imageFilter);

            fileChooser.setDialogTitle("Abrir arquivo");
            int result = fileChooser.showOpenDialog(null);
            if (result == 0) {
                ativarBotoesNoPainel(true);
                String filename = fileChooser.getSelectedFile().getAbsolutePath();
                nomeDoArquivoSalvar = fileChooser.getSelectedFile().getName();
                bufferIn = ImageIO.read(new File(filename));
                bufferOut = bufferIn;
                bufferOriginal = bufferIn;
                Image dimg = bufferIn.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),
                        Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                jLabel1.setIcon(imageIcon);
                jLabel1.setText(null);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    void aplicarFiltro(BufferedImage bufferInputIn) {
        // imad
        Image dimg = bufferIn.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),
                Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(((new ImageIcon(bufferInputIn))
                .getImage().getScaledInstance(jLabel1.getWidth(),
                        jLabel1.getHeight(), Image.SCALE_SMOOTH))));
    }

    private void jButtonCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCinzaActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setEscalaCinza(bufferIn);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonCinzaActionPerformed

    private void jButtonSepiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSepiaActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setSepia(bufferIn);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonSepiaActionPerformed

    private void jButtonThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThresholdActionPerformed
        // TODO add your handling code here:,
        bufferOut = new Filtro().setThreshold(bufferIn);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonThresholdActionPerformed

    private void jButtonNegativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativaActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setNegativa(bufferIn);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonNegativaActionPerformed
    void definirImagemPadrao() {
        jLabel1.setIcon(new ImageIcon(((new ImageIcon(getClass().getResource("/imagens/white.png")).getImage()
                .getScaledInstance(600, 600, Image.SCALE_SMOOTH)))));
    }
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
//        jLabel2.setText(DAO.getColor().toString());
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOriginalActionPerformed
        // TODO add your handling code here:
        aplicarFiltro(bufferOriginal);
    }//GEN-LAST:event_jButtonOriginalActionPerformed

    private void jButtonColorizacaoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoRedActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setColorizacao(bufferIn, 1);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoRedActionPerformed

    private void jButtonColorizacaoBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoBlueActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setColorizacao(bufferIn, 2);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoBlueActionPerformed

    private void jButtonColorizacaoGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorizacaoGreenActionPerformed
        // TODO add your handling code here:
        bufferOut = new Filtro().setColorizacao(bufferIn, 3);
        aplicarFiltro(bufferOut);
    }//GEN-LAST:event_jButtonColorizacaoGreenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abrirArquivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         if (bufferOut == null) {
            JOptionPane.showMessageDialog(null, "Nenhuma imagem selecionada", "Atenção", 1);
        } else {
            Filtro filtro = new Filtro();
            filtro.save(bufferOut, nomeDoArquivoSalvar);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          definirImagemPadrao();
        ativarBotoesNoPainel(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog abrirArquivoDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCinza;
    private javax.swing.JButton jButtonColorizacaoBlue;
    private javax.swing.JButton jButtonColorizacaoGreen;
    private javax.swing.JButton jButtonColorizacaoRed;
    private javax.swing.JButton jButtonNegativa;
    private javax.swing.JButton jButtonOriginal;
    private javax.swing.JButton jButtonSepia;
    private javax.swing.JButton jButtonThreshold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
